function split_data = kmean_split(data,splits)
%Clusteres a data set based on kmeans and splits the data accordingly based
%on the number of groups(splits). Returns a cell array of vectors
%generated by the kmeans clustering.
split_data = cell(1,splits);
k_clustered = kmeans(data,splits);
for c1 = 1:splits
    temp = [];
    for c2 = 1:size(k_clustered,1)
        if k_clustered(c2) == c1
            split_data{c1} = [split_data{c1};data(c2,:)];
        end
    end
end
end

